version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imcchart
    image: yknam/imcchart
    volumes:
      - ./src:/app/src
    ports:
      - "5009:80"
