import React from "react";
import "./App.css";
import EasyChart from "./Chart/EasyChart";

const App = () => {
  return (
    <div style={{ flexGrow: 1, margin: 10 }}>
      <EasyChart edit={false} authObj={sampledata} showmenu={true} />
    </div>
  );
};

export default App;

const sampledata = {
  setting: {
    title: "Sales by Country",
    charttype: "pie",
    xField: "Country",
    yField: "Sales",
    aggregate: "sum",
    series: "",
  },
  dtlist: [
    {
      Country: "Canada",
      Product: "Carretera",
      UnitsSold: 1618.5,
      ManufacturingPrice: 3,
      SalePrice: 20,
      GrossSales: 32370,
      Sales: 32370,
    },
    {
      Country: "Germany",
      Product: "Carretera",
      UnitsSold: 1321,
      ManufacturingPrice: 3,
      SalePrice: 20,
      GrossSales: 26420,
      Sales: 26420,
    },
    {
      Country: "France",
      Product: "Carretera",
      UnitsSold: 2178,
      ManufacturingPrice: 3,
      SalePrice: 15,
      GrossSales: 32670,
      Sales: 32670,
    },
    {
      Country: "Germany",
      Product: "Carretera",
      UnitsSold: 888,
      ManufacturingPrice: 3,
      SalePrice: 15,
      GrossSales: 13320,
      Sales: 13320,
    },
    {
      Country: "Mexico",
      Product: "Carretera",
      UnitsSold: 2470,
      ManufacturingPrice: 3,
      SalePrice: 15,
      GrossSales: 37050,
      Sales: 37050,
    },
    {
      Country: "Germany",
      Product: "Carretera",
      UnitsSold: 1513,
      ManufacturingPrice: 3,
      SalePrice: 350,
      GrossSales: 529550,
      Sales: 529550,
    },
    {
      Country: "Germany",
      Product: "Montana",
      UnitsSold: 921,
      ManufacturingPrice: 5,
      SalePrice: 15,
      GrossSales: 13815,
      Sales: 13815,
    },
    {
      Country: "Canada",
      Product: "Montana",
      UnitsSold: 2518,
      ManufacturingPrice: 5,
      SalePrice: 12,
      GrossSales: 30216,
      Sales: 30216,
    },
    {
      Country: "France",
      Product: "Montana",
      UnitsSold: 1899,
      ManufacturingPrice: 5,
      SalePrice: 20,
      GrossSales: 37980,
      Sales: 37980,
    },
    {
      Country: "Germany",
      Product: "Montana",
      UnitsSold: 1545,
      ManufacturingPrice: 5,
      SalePrice: 12,
      GrossSales: 18540,
      Sales: 18540,
    },
    {
      Country: "Mexico",
      Product: "Montana",
      UnitsSold: 2470,
      ManufacturingPrice: 5,
      SalePrice: 15,
      GrossSales: 37050,
      Sales: 37050,
    },
    {
      Country: "Canada",
      Product: "Montana",
      UnitsSold: 2665.5,
      ManufacturingPrice: 5,
      SalePrice: 125,
      GrossSales: 333187.5,
      Sales: 333187.5,
    },
    {
      Country: "Mexico",
      Product: "Montana",
      UnitsSold: 958,
      ManufacturingPrice: 5,
      SalePrice: 300,
      GrossSales: 287400,
      Sales: 287400,
    },
    {
      Country: "Germany",
      Product: "Montana",
      UnitsSold: 2146,
      ManufacturingPrice: 5,
      SalePrice: 7,
      GrossSales: 15022,
      Sales: 15022,
    },
    {
      Country: "Canada",
      Product: "Montana",
      UnitsSold: 345,
      ManufacturingPrice: 5,
      SalePrice: 125,
      GrossSales: 43125,
      Sales: 43125,
    },
    {
      Country: "USA",
      Product: "Montana",
      UnitsSold: 615,
      ManufacturingPrice: 5,
      SalePrice: 15,
      GrossSales: 9225,
      Sales: 9225,
    },
    {
      Country: "Canada",
      Product: "Paseo",
      UnitsSold: 292,
      ManufacturingPrice: 10,
      SalePrice: 20,
      GrossSales: 5840,
      Sales: 5840,
    },
    {
      Country: "Mexico",
      Product: "Paseo",
      UnitsSold: 974,
      ManufacturingPrice: 10,
      SalePrice: 15,
      GrossSales: 14610,
      Sales: 14610,
    },
    {
      Country: "Canada",
      Product: "Paseo",
      UnitsSold: 2518,
      ManufacturingPrice: 10,
      SalePrice: 12,
      GrossSales: 30216,
      Sales: 30216,
    },
    {
      Country: "Germany",
      Product: "Paseo",
      UnitsSold: 1006,
      ManufacturingPrice: 10,
      SalePrice: 350,
      GrossSales: 352100,
      Sales: 352100,
    },
    {
      Country: "Germany",
      Product: "Paseo",
      UnitsSold: 367,
      ManufacturingPrice: 10,
      SalePrice: 12,
      GrossSales: 4404,
      Sales: 4404,
    },
    {
      Country: "Mexico",
      Product: "Paseo",
      UnitsSold: 883,
      ManufacturingPrice: 10,
      SalePrice: 7,
      GrossSales: 6181,
      Sales: 6181,
    },
    {
      Country: "France",
      Product: "Paseo",
      UnitsSold: 549,
      ManufacturingPrice: 10,
      SalePrice: 15,
      GrossSales: 8235,
      Sales: 8235,
    },
    {
      Country: "Mexico",
      Product: "Paseo",
      UnitsSold: 788,
      ManufacturingPrice: 10,
      SalePrice: 300,
      GrossSales: 236400,
      Sales: 236400,
    },
    {
      Country: "Mexico",
      Product: "Paseo",
      UnitsSold: 2472,
      ManufacturingPrice: 10,
      SalePrice: 15,
      GrossSales: 37080,
      Sales: 37080,
    },
    {
      Country: "USA",
      Product: "Paseo",
      UnitsSold: 1143,
      ManufacturingPrice: 10,
      SalePrice: 7,
      GrossSales: 8001,
      Sales: 8001,
    },
    {
      Country: "Canada",
      Product: "Paseo",
      UnitsSold: 1725,
      ManufacturingPrice: 10,
      SalePrice: 350,
      GrossSales: 603750,
      Sales: 603750,
    },
    {
      Country: "USA",
      Product: "Paseo",
      UnitsSold: 912,
      ManufacturingPrice: 10,
      SalePrice: 12,
      GrossSales: 10944,
      Sales: 10944,
    },
    {
      Country: "Canada",
      Product: "Paseo",
      UnitsSold: 2152,
      ManufacturingPrice: 10,
      SalePrice: 15,
      GrossSales: 32280,
      Sales: 32280,
    },
    {
      Country: "Canada",
      Product: "Paseo",
      UnitsSold: 1817,
      ManufacturingPrice: 10,
      SalePrice: 20,
      GrossSales: 36340,
      Sales: 36340,
    },
    {
      Country: "Germany",
      Product: "Paseo",
      UnitsSold: 1513,
      ManufacturingPrice: 10,
      SalePrice: 350,
      GrossSales: 529550,
      Sales: 529550,
    },
    {
      Country: "Mexico",
      Product: "Velo",
      UnitsSold: 1493,
      ManufacturingPrice: 120,
      SalePrice: 7,
      GrossSales: 10451,
      Sales: 10451,
    },
    {
      Country: "France",
      Product: "Velo",
      UnitsSold: 1804,
      ManufacturingPrice: 120,
      SalePrice: 125,
      GrossSales: 225500,
      Sales: 225500,
    },
    {
      Country: "Germany",
      Product: "Velo",
      UnitsSold: 2161,
      ManufacturingPrice: 120,
      SalePrice: 12,
      GrossSales: 25932,
      Sales: 25932,
    },
    {
      Country: "Germany",
      Product: "Velo",
      UnitsSold: 1006,
      ManufacturingPrice: 120,
      SalePrice: 350,
      GrossSales: 352100,
      Sales: 352100,
    },
  ],
};
